# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs3/auth/v0alpha/resources.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cs3.types import types_pb2 as cs3_dot_types_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs3/auth/v0alpha/resources.proto',
  package='cs3.authv0alpha',
  syntax='proto3',
  serialized_options=_b('\n\023com.cs3.authv0alphaB\016ResourcesProtoP\001Z\rauthv0alphapb\242\002\006CBOXAB\252\002\017CS3.AuthV0Alpha\312\002\017CS3\\AuthV0Alpha'),
  serialized_pb=_b('\n cs3/auth/v0alpha/resources.proto\x12\x0f\x63s3.authv0alpha\x1a\x15\x63s3/types/types.proto\"\xaf\x01\n\x04User\x12\x1d\n\x02id\x18\x01 \x01(\x0b\x32\x11.cs3.types.UserId\x12\x0e\n\x06issuer\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x0c\n\x04mail\x18\x05 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x06 \x01(\t\x12\x0e\n\x06groups\x18\x07 \x03(\t\x12!\n\x06opaque\x18\x08 \x01(\x0b\x32\x11.cs3.types.OpaqueBc\n\x13\x63om.cs3.authv0alphaB\x0eResourcesProtoP\x01Z\rauthv0alphapb\xa2\x02\x06\x43\x42OXAB\xaa\x02\x0f\x43S3.AuthV0Alpha\xca\x02\x0f\x43S3\\AuthV0Alphab\x06proto3')
  ,
  dependencies=[cs3_dot_types_dot_types__pb2.DESCRIPTOR,])




_USER = _descriptor.Descriptor(
  name='User',
  full_name='cs3.authv0alpha.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cs3.authv0alpha.User.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issuer', full_name='cs3.authv0alpha.User.issuer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='cs3.authv0alpha.User.subject', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='cs3.authv0alpha.User.username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mail', full_name='cs3.authv0alpha.User.mail', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='cs3.authv0alpha.User.display_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groups', full_name='cs3.authv0alpha.User.groups', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opaque', full_name='cs3.authv0alpha.User.opaque', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=252,
)

_USER.fields_by_name['id'].message_type = cs3_dot_types_dot_types__pb2._USERID
_USER.fields_by_name['opaque'].message_type = cs3_dot_types_dot_types__pb2._OPAQUE
DESCRIPTOR.message_types_by_name['User'] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'cs3.auth.v0alpha.resources_pb2'
  # @@protoc_insertion_point(class_scope:cs3.authv0alpha.User)
  })
_sym_db.RegisterMessage(User)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
