---
kind: pipeline
name: publish_dev

trigger:
  branch:
  - main
  event:
    exclude:
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: pypi_publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
    distributions:
    - sdist
    - bdist_wheel

---
kind: pipeline
name: publish

trigger:
  event:
    include:
    - tag

steps:
- name: pypi_publish
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_username
    password:
      from_secret: pypi_password
    distributions:
    - sdist
    - bdist_wheel
