# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs3/storage/registry/v1beta1/resources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cs3.types.v1beta1 import types_pb2 as cs3_dot_types_dot_v1beta1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,cs3/storage/registry/v1beta1/resources.proto\x12\x1c\x63s3.storage.registry.v1beta1\x1a\x1d\x63s3/types/v1beta1/types.proto\"\x86\x02\n\x0cProviderInfo\x12)\n\x06opaque\x18\x01 \x01(\x0b\x32\x19.cs3.types.v1beta1.Opaque\x12\x13\n\x0bprovider_id\x18\x02 \x01(\t\x12\x15\n\rprovider_path\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x45\n\x08\x66\x65\x61tures\x18\x06 \x01(\x0b\x32\x33.cs3.storage.registry.v1beta1.ProviderInfo.Features\x1a\x32\n\x08\x46\x65\x61tures\x12\x0f\n\x07recycle\x18\x01 \x01(\x08\x12\x15\n\rfile_versions\x18\x02 \x01(\x08\x42\x89\x01\n com.cs3.storage.registry.v1beta1B\x0eResourcesProtoP\x01Z\x0fregistryv1beta1\xa2\x02\x03\x43SR\xaa\x02\x1c\x43s3.Storage.Registry.V1Beta1\xca\x02\x1c\x43s3\\Storage\\Registry\\V1Beta1b\x06proto3')



_PROVIDERINFO = DESCRIPTOR.message_types_by_name['ProviderInfo']
_PROVIDERINFO_FEATURES = _PROVIDERINFO.nested_types_by_name['Features']
ProviderInfo = _reflection.GeneratedProtocolMessageType('ProviderInfo', (_message.Message,), {

  'Features' : _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), {
    'DESCRIPTOR' : _PROVIDERINFO_FEATURES,
    '__module__' : 'cs3.storage.registry.v1beta1.resources_pb2'
    # @@protoc_insertion_point(class_scope:cs3.storage.registry.v1beta1.ProviderInfo.Features)
    })
  ,
  'DESCRIPTOR' : _PROVIDERINFO,
  '__module__' : 'cs3.storage.registry.v1beta1.resources_pb2'
  # @@protoc_insertion_point(class_scope:cs3.storage.registry.v1beta1.ProviderInfo)
  })
_sym_db.RegisterMessage(ProviderInfo)
_sym_db.RegisterMessage(ProviderInfo.Features)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n com.cs3.storage.registry.v1beta1B\016ResourcesProtoP\001Z\017registryv1beta1\242\002\003CSR\252\002\034Cs3.Storage.Registry.V1Beta1\312\002\034Cs3\\Storage\\Registry\\V1Beta1'
  _PROVIDERINFO._serialized_start=110
  _PROVIDERINFO._serialized_end=372
  _PROVIDERINFO_FEATURES._serialized_start=322
  _PROVIDERINFO_FEATURES._serialized_end=372
# @@protoc_insertion_point(module_scope)
