# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs3/sharing/link/v1beta1/resources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cs3.identity.user.v1beta1 import resources_pb2 as cs3_dot_identity_dot_user_dot_v1beta1_dot_resources__pb2
from cs3.storage.provider.v1beta1 import resources_pb2 as cs3_dot_storage_dot_provider_dot_v1beta1_dot_resources__pb2
from cs3.types.v1beta1 import types_pb2 as cs3_dot_types_dot_v1beta1_dot_types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs3/sharing/link/v1beta1/resources.proto',
  package='cs3.sharing.link.v1beta1',
  syntax='proto3',
  serialized_options=b'\n\034com.cs3.sharing.link.v1beta1B\016ResourcesProtoP\001Z\013linkv1beta1\242\002\003CSL\252\002\030Cs3.Sharing.Link.V1Beta1\312\002\030Cs3\\Sharing\\Link\\V1Beta1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(cs3/sharing/link/v1beta1/resources.proto\x12\x18\x63s3.sharing.link.v1beta1\x1a)cs3/identity/user/v1beta1/resources.proto\x1a,cs3/storage/provider/v1beta1/resources.proto\x1a\x1d\x63s3/types/v1beta1/types.proto\"\xfb\x03\n\x0bPublicShare\x12\x33\n\x02id\x18\x01 \x01(\x0b\x32\'.cs3.sharing.link.v1beta1.PublicShareId\x12\r\n\x05token\x18\x02 \x01(\t\x12=\n\x0bresource_id\x18\x03 \x01(\x0b\x32(.cs3.storage.provider.v1beta1.ResourceId\x12\x45\n\x0bpermissions\x18\x04 \x01(\x0b\x32\x30.cs3.sharing.link.v1beta1.PublicSharePermissions\x12\x30\n\x05owner\x18\x05 \x01(\x0b\x32!.cs3.identity.user.v1beta1.UserId\x12\x32\n\x07\x63reator\x18\x06 \x01(\x0b\x32!.cs3.identity.user.v1beta1.UserId\x12+\n\x05\x63time\x18\x07 \x01(\x0b\x32\x1c.cs3.types.v1beta1.Timestamp\x12+\n\x05mtime\x18\x08 \x01(\x0b\x32\x1c.cs3.types.v1beta1.Timestamp\x12\x1a\n\x12password_protected\x18\t \x01(\x08\x12\x30\n\nexpiration\x18\n \x01(\x0b\x32\x1c.cs3.types.v1beta1.Timestamp\x12\x14\n\x0c\x64isplay_name\x18\x0b \x01(\t\"`\n\x16PublicSharePermissions\x12\x46\n\x0bpermissions\x18\x01 \x01(\x0b\x32\x31.cs3.storage.provider.v1beta1.ResourcePermissions\"\"\n\rPublicShareId\x12\x11\n\topaque_id\x18\x02 \x01(\t\"f\n\x14PublicShareReference\x12\x35\n\x02id\x18\x01 \x01(\x0b\x32\'.cs3.sharing.link.v1beta1.PublicShareIdH\x00\x12\x0f\n\x05token\x18\x02 \x01(\tH\x00\x42\x06\n\x04spec\"\x92\x01\n\x05Grant\x12\x45\n\x0bpermissions\x18\x01 \x01(\x0b\x32\x30.cs3.sharing.link.v1beta1.PublicSharePermissions\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x30\n\nexpiration\x18\x03 \x01(\x0b\x32\x1c.cs3.types.v1beta1.TimestampBy\n\x1c\x63om.cs3.sharing.link.v1beta1B\x0eResourcesProtoP\x01Z\x0blinkv1beta1\xa2\x02\x03\x43SL\xaa\x02\x18\x43s3.Sharing.Link.V1Beta1\xca\x02\x18\x43s3\\Sharing\\Link\\V1Beta1b\x06proto3'
  ,
  dependencies=[cs3_dot_identity_dot_user_dot_v1beta1_dot_resources__pb2.DESCRIPTOR,cs3_dot_storage_dot_provider_dot_v1beta1_dot_resources__pb2.DESCRIPTOR,cs3_dot_types_dot_v1beta1_dot_types__pb2.DESCRIPTOR,])




_PUBLICSHARE = _descriptor.Descriptor(
  name='PublicShare',
  full_name='cs3.sharing.link.v1beta1.PublicShare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cs3.sharing.link.v1beta1.PublicShare.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='cs3.sharing.link.v1beta1.PublicShare.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_id', full_name='cs3.sharing.link.v1beta1.PublicShare.resource_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='permissions', full_name='cs3.sharing.link.v1beta1.PublicShare.permissions', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner', full_name='cs3.sharing.link.v1beta1.PublicShare.owner', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creator', full_name='cs3.sharing.link.v1beta1.PublicShare.creator', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='cs3.sharing.link.v1beta1.PublicShare.ctime', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mtime', full_name='cs3.sharing.link.v1beta1.PublicShare.mtime', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password_protected', full_name='cs3.sharing.link.v1beta1.PublicShare.password_protected', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='cs3.sharing.link.v1beta1.PublicShare.expiration', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='cs3.sharing.link.v1beta1.PublicShare.display_name', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=698,
)


_PUBLICSHAREPERMISSIONS = _descriptor.Descriptor(
  name='PublicSharePermissions',
  full_name='cs3.sharing.link.v1beta1.PublicSharePermissions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissions', full_name='cs3.sharing.link.v1beta1.PublicSharePermissions.permissions', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=796,
)


_PUBLICSHAREID = _descriptor.Descriptor(
  name='PublicShareId',
  full_name='cs3.sharing.link.v1beta1.PublicShareId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='opaque_id', full_name='cs3.sharing.link.v1beta1.PublicShareId.opaque_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=798,
  serialized_end=832,
)


_PUBLICSHAREREFERENCE = _descriptor.Descriptor(
  name='PublicShareReference',
  full_name='cs3.sharing.link.v1beta1.PublicShareReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='cs3.sharing.link.v1beta1.PublicShareReference.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='cs3.sharing.link.v1beta1.PublicShareReference.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='spec', full_name='cs3.sharing.link.v1beta1.PublicShareReference.spec',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=834,
  serialized_end=936,
)


_GRANT = _descriptor.Descriptor(
  name='Grant',
  full_name='cs3.sharing.link.v1beta1.Grant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='permissions', full_name='cs3.sharing.link.v1beta1.Grant.permissions', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='cs3.sharing.link.v1beta1.Grant.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiration', full_name='cs3.sharing.link.v1beta1.Grant.expiration', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=939,
  serialized_end=1085,
)

_PUBLICSHARE.fields_by_name['id'].message_type = _PUBLICSHAREID
_PUBLICSHARE.fields_by_name['resource_id'].message_type = cs3_dot_storage_dot_provider_dot_v1beta1_dot_resources__pb2._RESOURCEID
_PUBLICSHARE.fields_by_name['permissions'].message_type = _PUBLICSHAREPERMISSIONS
_PUBLICSHARE.fields_by_name['owner'].message_type = cs3_dot_identity_dot_user_dot_v1beta1_dot_resources__pb2._USERID
_PUBLICSHARE.fields_by_name['creator'].message_type = cs3_dot_identity_dot_user_dot_v1beta1_dot_resources__pb2._USERID
_PUBLICSHARE.fields_by_name['ctime'].message_type = cs3_dot_types_dot_v1beta1_dot_types__pb2._TIMESTAMP
_PUBLICSHARE.fields_by_name['mtime'].message_type = cs3_dot_types_dot_v1beta1_dot_types__pb2._TIMESTAMP
_PUBLICSHARE.fields_by_name['expiration'].message_type = cs3_dot_types_dot_v1beta1_dot_types__pb2._TIMESTAMP
_PUBLICSHAREPERMISSIONS.fields_by_name['permissions'].message_type = cs3_dot_storage_dot_provider_dot_v1beta1_dot_resources__pb2._RESOURCEPERMISSIONS
_PUBLICSHAREREFERENCE.fields_by_name['id'].message_type = _PUBLICSHAREID
_PUBLICSHAREREFERENCE.oneofs_by_name['spec'].fields.append(
  _PUBLICSHAREREFERENCE.fields_by_name['id'])
_PUBLICSHAREREFERENCE.fields_by_name['id'].containing_oneof = _PUBLICSHAREREFERENCE.oneofs_by_name['spec']
_PUBLICSHAREREFERENCE.oneofs_by_name['spec'].fields.append(
  _PUBLICSHAREREFERENCE.fields_by_name['token'])
_PUBLICSHAREREFERENCE.fields_by_name['token'].containing_oneof = _PUBLICSHAREREFERENCE.oneofs_by_name['spec']
_GRANT.fields_by_name['permissions'].message_type = _PUBLICSHAREPERMISSIONS
_GRANT.fields_by_name['expiration'].message_type = cs3_dot_types_dot_v1beta1_dot_types__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PublicShare'] = _PUBLICSHARE
DESCRIPTOR.message_types_by_name['PublicSharePermissions'] = _PUBLICSHAREPERMISSIONS
DESCRIPTOR.message_types_by_name['PublicShareId'] = _PUBLICSHAREID
DESCRIPTOR.message_types_by_name['PublicShareReference'] = _PUBLICSHAREREFERENCE
DESCRIPTOR.message_types_by_name['Grant'] = _GRANT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicShare = _reflection.GeneratedProtocolMessageType('PublicShare', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICSHARE,
  '__module__' : 'cs3.sharing.link.v1beta1.resources_pb2'
  # @@protoc_insertion_point(class_scope:cs3.sharing.link.v1beta1.PublicShare)
  })
_sym_db.RegisterMessage(PublicShare)

PublicSharePermissions = _reflection.GeneratedProtocolMessageType('PublicSharePermissions', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICSHAREPERMISSIONS,
  '__module__' : 'cs3.sharing.link.v1beta1.resources_pb2'
  # @@protoc_insertion_point(class_scope:cs3.sharing.link.v1beta1.PublicSharePermissions)
  })
_sym_db.RegisterMessage(PublicSharePermissions)

PublicShareId = _reflection.GeneratedProtocolMessageType('PublicShareId', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICSHAREID,
  '__module__' : 'cs3.sharing.link.v1beta1.resources_pb2'
  # @@protoc_insertion_point(class_scope:cs3.sharing.link.v1beta1.PublicShareId)
  })
_sym_db.RegisterMessage(PublicShareId)

PublicShareReference = _reflection.GeneratedProtocolMessageType('PublicShareReference', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICSHAREREFERENCE,
  '__module__' : 'cs3.sharing.link.v1beta1.resources_pb2'
  # @@protoc_insertion_point(class_scope:cs3.sharing.link.v1beta1.PublicShareReference)
  })
_sym_db.RegisterMessage(PublicShareReference)

Grant = _reflection.GeneratedProtocolMessageType('Grant', (_message.Message,), {
  'DESCRIPTOR' : _GRANT,
  '__module__' : 'cs3.sharing.link.v1beta1.resources_pb2'
  # @@protoc_insertion_point(class_scope:cs3.sharing.link.v1beta1.Grant)
  })
_sym_db.RegisterMessage(Grant)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
