# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from cs3.appregistry.v0alpha import appregistry_pb2 as cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2
from cs3.authregistry.v0alpha import authregistry_pb2 as cs3_dot_authregistry_dot_v0alpha_dot_authregistry__pb2
from cs3.gateway.v0alpha import gateway_pb2 as cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2
from cs3.ocmshareprovider.v0alpha import ocmshareprovider_pb2 as cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2
from cs3.preferences.v0alpha import preferences_pb2 as cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2
from cs3.publicshareprovider.v0alpha import publicshareprovider_pb2 as cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2
from cs3.storageprovider.v0alpha import storageprovider_pb2 as cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2
from cs3.storageregistry.v0alpha import storageregistry_pb2 as cs3_dot_storageregistry_dot_v0alpha_dot_storageregistry__pb2
from cs3.userprovider.v0alpha import userprovider_pb2 as cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2
from cs3.usershareprovider.v0alpha import usershareprovider_pb2 as cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2


class GatewayServiceStub(object):
  """Gateway API

  The Gateway API is the only API exposed direclty to end-clients.
  It is a facade API that all clients should connect to.
  Other APIS like the StorageProviderAPI are internal APIS.

  The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
  NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
  "OPTIONAL" in this document are to be interpreted as described in
  RFC 2119.

  The following are global requirements that apply to all methods:
  Any method MUST return CODE_OK on a succesful operation.
  Any method MAY return NOT_IMPLEMENTED.
  Any method MAY return INTERNAL.
  Any method MAY return UNKNOWN.
  Any method MAY return UNAUTHENTICATED.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Authenticate = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/Authenticate',
        request_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.AuthenticateRequest.SerializeToString,
        response_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.AuthenticateResponse.FromString,
        )
    self.WhoAmI = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/WhoAmI',
        request_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.WhoAmIRequest.SerializeToString,
        response_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.WhoAmIResponse.FromString,
        )
    self.CreateContainer = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/CreateContainer',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.CreateContainerRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.CreateContainerResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/Delete',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.DeleteRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.DeleteResponse.FromString,
        )
    self.GetPath = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetPath',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.GetPathRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.GetPathResponse.FromString,
        )
    self.GetQuota = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetQuota',
        request_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.GetQuotaRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.GetQuotaResponse.FromString,
        )
    self.InitiateFileDownload = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/InitiateFileDownload',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.InitiateFileDownloadRequest.SerializeToString,
        response_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.InitiateFileDownloadResponse.FromString,
        )
    self.InitiateFileUpload = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/InitiateFileUpload',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.InitiateFileUploadRequest.SerializeToString,
        response_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.InitiateFileUploadResponse.FromString,
        )
    self.ListContainerStream = channel.unary_stream(
        '/cs3.gatewayv0alpha.GatewayService/ListContainerStream',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerStreamRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerStreamResponse.FromString,
        )
    self.ListContainer = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListContainer',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerResponse.FromString,
        )
    self.ListFileVersions = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListFileVersions',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListFileVersionsRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListFileVersionsResponse.FromString,
        )
    self.ListRecycleStream = channel.unary_stream(
        '/cs3.gatewayv0alpha.GatewayService/ListRecycleStream',
        request_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.ListRecycleStreamRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListRecycleStreamResponse.FromString,
        )
    self.ListRecycle = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListRecycle',
        request_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.ListRecycleRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListRecycleResponse.FromString,
        )
    self.Move = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/Move',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.MoveRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.MoveResponse.FromString,
        )
    self.PurgeRecycle = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/PurgeRecycle',
        request_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.PurgeRecycleRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.PurgeRecycleResponse.FromString,
        )
    self.RestoreFileVersion = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/RestoreFileVersion',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreFileVersionRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreFileVersionResponse.FromString,
        )
    self.RestoreRecycleItem = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/RestoreRecycleItem',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreRecycleItemRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreRecycleItemResponse.FromString,
        )
    self.Stat = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/Stat',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.StatRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.StatResponse.FromString,
        )
    self.SetArbitraryMetadata = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/SetArbitraryMetadata',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.SetArbitraryMetadataRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.SetArbitraryMetadataResponse.FromString,
        )
    self.UnsetArbitraryMetadata = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/UnsetArbitraryMetadata',
        request_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.UnsetArbitraryMetadataRequest.SerializeToString,
        response_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.UnsetArbitraryMetadataResponse.FromString,
        )
    self.CreateShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/CreateShare',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.CreateShareRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.CreateShareResponse.FromString,
        )
    self.RemoveShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/RemoveShare',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.RemoveShareRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.RemoveShareResponse.FromString,
        )
    self.GetShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetShare',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetShareRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetShareResponse.FromString,
        )
    self.ListShares = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListShares',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListSharesRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListSharesResponse.FromString,
        )
    self.UpdateShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/UpdateShare',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateShareRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateShareResponse.FromString,
        )
    self.ListReceivedShares = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListReceivedShares',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListReceivedSharesRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListReceivedSharesResponse.FromString,
        )
    self.UpdateReceivedShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/UpdateReceivedShare',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateReceivedShareRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateReceivedShareResponse.FromString,
        )
    self.GetReceivedShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetReceivedShare',
        request_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetReceivedShareRequest.SerializeToString,
        response_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetReceivedShareResponse.FromString,
        )
    self.SetKey = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/SetKey',
        request_serializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.SetKeyRequest.SerializeToString,
        response_deserializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.SetKeyResponse.FromString,
        )
    self.GetKey = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetKey',
        request_serializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.GetKeyRequest.SerializeToString,
        response_deserializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.GetKeyResponse.FromString,
        )
    self.CreatePublicShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/CreatePublicShare',
        request_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.CreatePublicShareRequest.SerializeToString,
        response_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.CreatePublicShareResponse.FromString,
        )
    self.RemovePublicShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/RemovePublicShare',
        request_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.RemovePublicShareRequest.SerializeToString,
        response_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.RemovePublicShareResponse.FromString,
        )
    self.GetPublicShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetPublicShare',
        request_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareRequest.SerializeToString,
        response_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareResponse.FromString,
        )
    self.GetPublicShareByToken = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetPublicShareByToken',
        request_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareByTokenRequest.SerializeToString,
        response_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareByTokenResponse.FromString,
        )
    self.ListPublicShares = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListPublicShares',
        request_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.ListPublicSharesRequest.SerializeToString,
        response_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.ListPublicSharesResponse.FromString,
        )
    self.UpdatePublicShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/UpdatePublicShare',
        request_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.UpdatePublicShareRequest.SerializeToString,
        response_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.UpdatePublicShareResponse.FromString,
        )
    self.CreateOCMShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/CreateOCMShare',
        request_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.CreateOCMShareRequest.SerializeToString,
        response_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.CreateOCMShareResponse.FromString,
        )
    self.RemoveOCMShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/RemoveOCMShare',
        request_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.RemoveOCMShareRequest.SerializeToString,
        response_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.RemoveOCMShareResponse.FromString,
        )
    self.GetOCMShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetOCMShare',
        request_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.GetOCMShareRequest.SerializeToString,
        response_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.GetOCMShareResponse.FromString,
        )
    self.ListOCMShares = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListOCMShares',
        request_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListOCMSharesRequest.SerializeToString,
        response_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListOCMSharesResponse.FromString,
        )
    self.UpdateOCMShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/UpdateOCMShare',
        request_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateOCMShareRequest.SerializeToString,
        response_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateOCMShareResponse.FromString,
        )
    self.ListReceivedOCMShares = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListReceivedOCMShares',
        request_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListReceivedOCMSharesRequest.SerializeToString,
        response_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListReceivedOCMSharesResponse.FromString,
        )
    self.UpdateReceivedOCMShare = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/UpdateReceivedOCMShare',
        request_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateReceivedOCMShareRequest.SerializeToString,
        response_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateReceivedOCMShareResponse.FromString,
        )
    self.GetAppProviders = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetAppProviders',
        request_serializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.GetAppProvidersRequest.SerializeToString,
        response_deserializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.GetAppProvidersResponse.FromString,
        )
    self.ListAppProviders = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListAppProviders',
        request_serializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.ListAppProvidersRequest.SerializeToString,
        response_deserializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.ListAppProvidersResponse.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetUser',
        request_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserRequest.SerializeToString,
        response_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserResponse.FromString,
        )
    self.GetUserGroups = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetUserGroups',
        request_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserGroupsRequest.SerializeToString,
        response_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserGroupsResponse.FromString,
        )
    self.IsInGroup = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/IsInGroup',
        request_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.IsInGroupRequest.SerializeToString,
        response_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.IsInGroupResponse.FromString,
        )
    self.FindUsers = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/FindUsers',
        request_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.FindUsersRequest.SerializeToString,
        response_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.FindUsersResponse.FromString,
        )
    self.ListAuthProviders = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/ListAuthProviders',
        request_serializer=cs3_dot_authregistry_dot_v0alpha_dot_authregistry__pb2.ListAuthProvidersRequest.SerializeToString,
        response_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.ListAuthProvidersResponse.FromString,
        )
    self.GetHome = channel.unary_unary(
        '/cs3.gatewayv0alpha.GatewayService/GetHome',
        request_serializer=cs3_dot_storageregistry_dot_v0alpha_dot_storageregistry__pb2.GetHomeRequest.SerializeToString,
        response_deserializer=cs3_dot_storageregistry_dot_v0alpha_dot_storageregistry__pb2.GetHomeResponse.FromString,
        )


class GatewayServiceServicer(object):
  """Gateway API

  The Gateway API is the only API exposed direclty to end-clients.
  It is a facade API that all clients should connect to.
  Other APIS like the StorageProviderAPI are internal APIS.

  The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
  NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and
  "OPTIONAL" in this document are to be interpreted as described in
  RFC 2119.

  The following are global requirements that apply to all methods:
  Any method MUST return CODE_OK on a succesful operation.
  Any method MAY return NOT_IMPLEMENTED.
  Any method MAY return INTERNAL.
  Any method MAY return UNKNOWN.
  Any method MAY return UNAUTHENTICATED.
  """

  def Authenticate(self, request, context):
    """*****************************************************************/
    ************************ AUTH ******** **************************/
    *****************************************************************/
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WhoAmI(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateContainer(self, request, context):
    """*****************************************************************/
    ************************ STORAGE PROVIDER ***********************/
    *****************************************************************/
    Creates a new resource of type container.
    MUST return CODE_PRECONDITION_FAILED if the container
    cannot be created at the specified reference.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Deletes a resource.
    If a resource specifies the non-empty container (directory, ...),
    then the entire directory is deleted recursively.
    If a resource specifies a reference or symlink type, only the reference is removed (not the target).
    MUST return CODE_NOT_FOUND if the reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPath(self, request, context):
    """Returns the path reference for
    the provided resource id reference.
    MUST return CODE_NOT_FOUND if the reference does not exist
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetQuota(self, request, context):
    """Returns the quota available under the provided
    reference.
    MUST return CODE_NOT_FOUND if the reference does not exist
    MUST return CODE_RESOURCE_EXHAUSTED on exceeded quota limits.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InitiateFileDownload(self, request, context):
    """Initiates the download of a file using an
    out-of-band data transfer mechanism.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InitiateFileUpload(self, request, context):
    """Initiates the upload of a file using an
    out-of-band data transfer mechanism.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListContainerStream(self, request, context):
    """Returns a stream of resource informations
    for the provided reference.
    MUST return CODE_NOT_FOUND if the reference does not exists.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListContainer(self, request, context):
    """Returns a list of resource information
    for the provided reference.
    MUST return CODE_NOT_FOUND if the reference does not exists.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListFileVersions(self, request, context):
    """Returns a list of the versions for a resource of
    type file at the provided reference.
    MUST return CODE_NOT_FOUND if the reference does not exist.
    MUST return CODE_OK and MUST return an empty list if no versions are available.
    TODO: What code if resource not of type file?
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListRecycleStream(self, request, context):
    """Returns a stream of recycle items for this storage provider.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListRecycle(self, request, context):
    """Returns a list of recycle items for this storage provider.
    MUST return CODE_OK and MUST return an empty list if no recycle items are available.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Move(self, request, context):
    """Moves a resource from one reference to another.
    MUST return CODE_NOT_FOUND if any of the references do not exist.
    MUST return CODE_PRECONDITION_FAILED if the source reference
    cannot be moved to the destination reference.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PurgeRecycle(self, request, context):
    """Permanently removes a recycle item from the recycle.
    This operation is irrevocable.
    MUST return CODE_NOT_FOUND if the recycle item id does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RestoreFileVersion(self, request, context):
    """Restores a file version for the provided reference.
    MUST return CODE_NOT_FOUND if the reference does not exist.
    MUST return CODE_NOT_FOUND if the version does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RestoreRecycleItem(self, request, context):
    """Restores a recycle item from the recycle.
    MUST return CODE_NOT_FOUND if the recycle item id does not exist.
    MUST return CODE_PRECONDITION_FAILED if the restore_path is non-empty
    and the recycle item cannot be restored to the restore_path.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stat(self, request, context):
    """Returns the resource information at the provided reference.
    MUST return CODE_NOT_FOUND if the reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetArbitraryMetadata(self, request, context):
    """Sets arbitrary metadata into a storage resource.
    Arbitrary metadata is returned in a cs3.storageproviderv0alpha.ResourceInfo.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnsetArbitraryMetadata(self, request, context):
    """Unsets arbitrary metdata into a storage resource.
    Arbitrary metadata is returned in a cs3.storageproviderv0alpha.ResourceInfo.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateShare(self, request, context):
    """*****************************************************************/
    ************************ USER SHARE PROVIDER ********************/
    *****************************************************************/
    Creates a new share.
    MUST return CODE_NOT_FOUND if the resource reference does not exist.
    MUST return CODE_ALREADY_EXISTS if the share already exists for the 4-tuple consisting of
    (owner, shared_resource, grantee).
    New shares MUST be created in the state SHARE_STATE_PENDING.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveShare(self, request, context):
    """Removes a share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetShare(self, request, context):
    """Gets share information for a single share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListShares(self, request, context):
    """List the shares the authproviderenticated principal has created,
    both as owner and creator. If a filter is specified, only
    shares satisfying the filter MUST be returned.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateShare(self, request, context):
    """Updates a share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListReceivedShares(self, request, context):
    """List all shares the authproviderenticated principal has received.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateReceivedShare(self, request, context):
    """Update the received share to change the share state or the display name.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetReceivedShare(self, request, context):
    """Get the information for the given received share reference.
    MUST return CODE_NOT_FOUND if the received share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetKey(self, request, context):
    """*****************************************************************/
    ************************ PREFERENCES ***************************/
    *****************************************************************/
    Maps the key-value pair.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKey(self, request, context):
    """Returns the value associated with the
    requested key.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePublicShare(self, request, context):
    """*****************************************************************/
    ************************ PUBLIC SHARE ***************************/
    *****************************************************************/
    Creates a new share.
    MUST return CODE_NOT_FOUND if the resource reference does not exist.
    MUST return CODE_ALREADY_EXISTS if the share already exists for the 4-tuple consisting of
    (owner, shared_resource, grantee).
    New shares MUST be created in the state SHARE_STATE_PENDING.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemovePublicShare(self, request, context):
    """Removes a share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPublicShare(self, request, context):
    """Gets share information for a single share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPublicShareByToken(self, request, context):
    """Gets share information for a single share by its unlisted token.
    MUST return CODE_NOT_FOUND if the share does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPublicShares(self, request, context):
    """List the shares the authproviderenticated principal has created,
    both as owner and creator. If a filter is specified, only
    shares satisfying the filter MUST be returned.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePublicShare(self, request, context):
    """Updates a share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateOCMShare(self, request, context):
    """*****************************************************************/
    ************************ OCM SHARE PROVIDER *********************/
    *****************************************************************/
    Creates a new ocm share.
    MUST return CODE_NOT_FOUND if the resource reference does not exist.
    MUST return CODE_ALREADY_EXISTS if the share already exists for the 4-tuple consisting of
    (owner, shared_resource, grantee).
    New shares MUST be created in the state SHARE_STATE_PENDING.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveOCMShare(self, request, context):
    """Removes a share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOCMShare(self, request, context):
    """Gets share information for a single share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListOCMShares(self, request, context):
    """List the shares the authproviderenticated principal has created,
    both as owner and creator. If a filter is specified, only
    shares satisfying the filter MUST be returned.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOCMShare(self, request, context):
    """Updates a share.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListReceivedOCMShares(self, request, context):
    """List all shares the authproviderenticated principal has received.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateReceivedOCMShare(self, request, context):
    """Update the received share to change the share state or the display name.
    MUST return CODE_NOT_FOUND if the share reference does not exist.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAppProviders(self, request, context):
    """*****************************************************************/
    ************************ APP REGISTRY ****************************/
    *****************************************************************/
    Returns the app providers that are capable of handling this resource info.
    MUST return CODE_NOT_FOUND if no providers are available.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAppProviders(self, request, context):
    """Returns a list of the available app providers known by this registry.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    """*****************************************************************/
    ************************ USER PROVIDER **************************/
    *****************************************************************/
    Gets the information about an user by its user id.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserGroups(self, request, context):
    """Gets the groups of a user.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsInGroup(self, request, context):
    """Tells if the user is in a certain group.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindUsers(self, request, context):
    """Finds users by any attribute of the user?
    TODO(labkode): to define the filters that make more sense.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAuthProviders(self, request, context):
    """*****************************************************************/
    ************************ AUTH REGISTRY  **************************/
    *****************************************************************/
    Returns a list of the available auth providers known by this registry.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHome(self, request, context):
    """************************ STORAGE REGISTRY ** ********************/
    *****************************************************************/
    Returns the home path for the given authenticated user.
    When a user has access to multiple storage providers, one of them is the home.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Authenticate': grpc.unary_unary_rpc_method_handler(
          servicer.Authenticate,
          request_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.AuthenticateRequest.FromString,
          response_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.AuthenticateResponse.SerializeToString,
      ),
      'WhoAmI': grpc.unary_unary_rpc_method_handler(
          servicer.WhoAmI,
          request_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.WhoAmIRequest.FromString,
          response_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.WhoAmIResponse.SerializeToString,
      ),
      'CreateContainer': grpc.unary_unary_rpc_method_handler(
          servicer.CreateContainer,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.CreateContainerRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.CreateContainerResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.DeleteRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.DeleteResponse.SerializeToString,
      ),
      'GetPath': grpc.unary_unary_rpc_method_handler(
          servicer.GetPath,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.GetPathRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.GetPathResponse.SerializeToString,
      ),
      'GetQuota': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuota,
          request_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.GetQuotaRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.GetQuotaResponse.SerializeToString,
      ),
      'InitiateFileDownload': grpc.unary_unary_rpc_method_handler(
          servicer.InitiateFileDownload,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.InitiateFileDownloadRequest.FromString,
          response_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.InitiateFileDownloadResponse.SerializeToString,
      ),
      'InitiateFileUpload': grpc.unary_unary_rpc_method_handler(
          servicer.InitiateFileUpload,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.InitiateFileUploadRequest.FromString,
          response_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.InitiateFileUploadResponse.SerializeToString,
      ),
      'ListContainerStream': grpc.unary_stream_rpc_method_handler(
          servicer.ListContainerStream,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerStreamRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerStreamResponse.SerializeToString,
      ),
      'ListContainer': grpc.unary_unary_rpc_method_handler(
          servicer.ListContainer,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListContainerResponse.SerializeToString,
      ),
      'ListFileVersions': grpc.unary_unary_rpc_method_handler(
          servicer.ListFileVersions,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListFileVersionsRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListFileVersionsResponse.SerializeToString,
      ),
      'ListRecycleStream': grpc.unary_stream_rpc_method_handler(
          servicer.ListRecycleStream,
          request_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.ListRecycleStreamRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListRecycleStreamResponse.SerializeToString,
      ),
      'ListRecycle': grpc.unary_unary_rpc_method_handler(
          servicer.ListRecycle,
          request_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.ListRecycleRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.ListRecycleResponse.SerializeToString,
      ),
      'Move': grpc.unary_unary_rpc_method_handler(
          servicer.Move,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.MoveRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.MoveResponse.SerializeToString,
      ),
      'PurgeRecycle': grpc.unary_unary_rpc_method_handler(
          servicer.PurgeRecycle,
          request_deserializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.PurgeRecycleRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.PurgeRecycleResponse.SerializeToString,
      ),
      'RestoreFileVersion': grpc.unary_unary_rpc_method_handler(
          servicer.RestoreFileVersion,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreFileVersionRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreFileVersionResponse.SerializeToString,
      ),
      'RestoreRecycleItem': grpc.unary_unary_rpc_method_handler(
          servicer.RestoreRecycleItem,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreRecycleItemRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.RestoreRecycleItemResponse.SerializeToString,
      ),
      'Stat': grpc.unary_unary_rpc_method_handler(
          servicer.Stat,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.StatRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.StatResponse.SerializeToString,
      ),
      'SetArbitraryMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.SetArbitraryMetadata,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.SetArbitraryMetadataRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.SetArbitraryMetadataResponse.SerializeToString,
      ),
      'UnsetArbitraryMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.UnsetArbitraryMetadata,
          request_deserializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.UnsetArbitraryMetadataRequest.FromString,
          response_serializer=cs3_dot_storageprovider_dot_v0alpha_dot_storageprovider__pb2.UnsetArbitraryMetadataResponse.SerializeToString,
      ),
      'CreateShare': grpc.unary_unary_rpc_method_handler(
          servicer.CreateShare,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.CreateShareRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.CreateShareResponse.SerializeToString,
      ),
      'RemoveShare': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveShare,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.RemoveShareRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.RemoveShareResponse.SerializeToString,
      ),
      'GetShare': grpc.unary_unary_rpc_method_handler(
          servicer.GetShare,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetShareRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetShareResponse.SerializeToString,
      ),
      'ListShares': grpc.unary_unary_rpc_method_handler(
          servicer.ListShares,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListSharesRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListSharesResponse.SerializeToString,
      ),
      'UpdateShare': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateShare,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateShareRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateShareResponse.SerializeToString,
      ),
      'ListReceivedShares': grpc.unary_unary_rpc_method_handler(
          servicer.ListReceivedShares,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListReceivedSharesRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.ListReceivedSharesResponse.SerializeToString,
      ),
      'UpdateReceivedShare': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateReceivedShare,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateReceivedShareRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.UpdateReceivedShareResponse.SerializeToString,
      ),
      'GetReceivedShare': grpc.unary_unary_rpc_method_handler(
          servicer.GetReceivedShare,
          request_deserializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetReceivedShareRequest.FromString,
          response_serializer=cs3_dot_usershareprovider_dot_v0alpha_dot_usershareprovider__pb2.GetReceivedShareResponse.SerializeToString,
      ),
      'SetKey': grpc.unary_unary_rpc_method_handler(
          servicer.SetKey,
          request_deserializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.SetKeyRequest.FromString,
          response_serializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.SetKeyResponse.SerializeToString,
      ),
      'GetKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetKey,
          request_deserializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.GetKeyRequest.FromString,
          response_serializer=cs3_dot_preferences_dot_v0alpha_dot_preferences__pb2.GetKeyResponse.SerializeToString,
      ),
      'CreatePublicShare': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePublicShare,
          request_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.CreatePublicShareRequest.FromString,
          response_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.CreatePublicShareResponse.SerializeToString,
      ),
      'RemovePublicShare': grpc.unary_unary_rpc_method_handler(
          servicer.RemovePublicShare,
          request_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.RemovePublicShareRequest.FromString,
          response_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.RemovePublicShareResponse.SerializeToString,
      ),
      'GetPublicShare': grpc.unary_unary_rpc_method_handler(
          servicer.GetPublicShare,
          request_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareRequest.FromString,
          response_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareResponse.SerializeToString,
      ),
      'GetPublicShareByToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetPublicShareByToken,
          request_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareByTokenRequest.FromString,
          response_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.GetPublicShareByTokenResponse.SerializeToString,
      ),
      'ListPublicShares': grpc.unary_unary_rpc_method_handler(
          servicer.ListPublicShares,
          request_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.ListPublicSharesRequest.FromString,
          response_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.ListPublicSharesResponse.SerializeToString,
      ),
      'UpdatePublicShare': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePublicShare,
          request_deserializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.UpdatePublicShareRequest.FromString,
          response_serializer=cs3_dot_publicshareprovider_dot_v0alpha_dot_publicshareprovider__pb2.UpdatePublicShareResponse.SerializeToString,
      ),
      'CreateOCMShare': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOCMShare,
          request_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.CreateOCMShareRequest.FromString,
          response_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.CreateOCMShareResponse.SerializeToString,
      ),
      'RemoveOCMShare': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveOCMShare,
          request_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.RemoveOCMShareRequest.FromString,
          response_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.RemoveOCMShareResponse.SerializeToString,
      ),
      'GetOCMShare': grpc.unary_unary_rpc_method_handler(
          servicer.GetOCMShare,
          request_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.GetOCMShareRequest.FromString,
          response_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.GetOCMShareResponse.SerializeToString,
      ),
      'ListOCMShares': grpc.unary_unary_rpc_method_handler(
          servicer.ListOCMShares,
          request_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListOCMSharesRequest.FromString,
          response_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListOCMSharesResponse.SerializeToString,
      ),
      'UpdateOCMShare': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOCMShare,
          request_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateOCMShareRequest.FromString,
          response_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateOCMShareResponse.SerializeToString,
      ),
      'ListReceivedOCMShares': grpc.unary_unary_rpc_method_handler(
          servicer.ListReceivedOCMShares,
          request_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListReceivedOCMSharesRequest.FromString,
          response_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.ListReceivedOCMSharesResponse.SerializeToString,
      ),
      'UpdateReceivedOCMShare': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateReceivedOCMShare,
          request_deserializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateReceivedOCMShareRequest.FromString,
          response_serializer=cs3_dot_ocmshareprovider_dot_v0alpha_dot_ocmshareprovider__pb2.UpdateReceivedOCMShareResponse.SerializeToString,
      ),
      'GetAppProviders': grpc.unary_unary_rpc_method_handler(
          servicer.GetAppProviders,
          request_deserializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.GetAppProvidersRequest.FromString,
          response_serializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.GetAppProvidersResponse.SerializeToString,
      ),
      'ListAppProviders': grpc.unary_unary_rpc_method_handler(
          servicer.ListAppProviders,
          request_deserializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.ListAppProvidersRequest.FromString,
          response_serializer=cs3_dot_appregistry_dot_v0alpha_dot_appregistry__pb2.ListAppProvidersResponse.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserRequest.FromString,
          response_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserResponse.SerializeToString,
      ),
      'GetUserGroups': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserGroups,
          request_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserGroupsRequest.FromString,
          response_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.GetUserGroupsResponse.SerializeToString,
      ),
      'IsInGroup': grpc.unary_unary_rpc_method_handler(
          servicer.IsInGroup,
          request_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.IsInGroupRequest.FromString,
          response_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.IsInGroupResponse.SerializeToString,
      ),
      'FindUsers': grpc.unary_unary_rpc_method_handler(
          servicer.FindUsers,
          request_deserializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.FindUsersRequest.FromString,
          response_serializer=cs3_dot_userprovider_dot_v0alpha_dot_userprovider__pb2.FindUsersResponse.SerializeToString,
      ),
      'ListAuthProviders': grpc.unary_unary_rpc_method_handler(
          servicer.ListAuthProviders,
          request_deserializer=cs3_dot_authregistry_dot_v0alpha_dot_authregistry__pb2.ListAuthProvidersRequest.FromString,
          response_serializer=cs3_dot_gateway_dot_v0alpha_dot_gateway__pb2.ListAuthProvidersResponse.SerializeToString,
      ),
      'GetHome': grpc.unary_unary_rpc_method_handler(
          servicer.GetHome,
          request_deserializer=cs3_dot_storageregistry_dot_v0alpha_dot_storageregistry__pb2.GetHomeRequest.FromString,
          response_serializer=cs3_dot_storageregistry_dot_v0alpha_dot_storageregistry__pb2.GetHomeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cs3.gatewayv0alpha.GatewayService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
